### ISSUE TITLE
ModuleNotFoundError: No module named 'error'

### ISSUE THREAD

**Issue by xvonabur** [Polidea/basset-ios#4]
Simply running `basset_ios` binary after installation results in following error:

```
Traceback (most recent call last):
File "/usr/local/Cellar/basset_ios/1.4.2/libexec/bin/basset_ios", line 5, in <module>
    import basset.basset_ios
  File "/usr/local/Cellar/basset_ios/1.4.2/libexec/basset/basset_ios.py", line 8, in <module>
    from basset.helpers.configuration_manager import ConfigurationManager
  File "/usr/local/Cellar/basset_ios/1.4.2/libexec/basset/helpers/configuration_manager.py", line 4, in <module
    import yaml
  File "/usr/local/Cellar/basset_ios/1.4.2/libexec/vendor/lib/python2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
```

**Comment by rogerluan** [comment]
It took me awhile to figure out how to solve this. I explained how to fix this here: https://github.com/Polidea/basset-ios/issues/3#issuecomment-687699822
